#!/usr/bin/env python

import os
from diffusers import StableDiffusionInpaintPipeline


model_id = "SG161222/Realistic_Vision_V5.1_noVAE"
MODEL_CACHE = "diffusers-cache"
os.makedirs(MODEL_CACHE, exist_ok=True)

pipe = StableDiffusionInpaintPipeline.from_pretrained(
    model_id,
    cache_dir=MODEL_CACHE,
)
